"""provider connections and stay source

Revision ID: 4dfd965adc45
Revises: 897482151541
Create Date: 2026-06-04 11:51:45.095120

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dfd965adc45'
down_revision: str | None = '897482151541'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('guest_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('genius_level', sa.Integer(), nullable=True),
    sa.Column('imported_stays', sa.Integer(), nullable=False),
    sa.Column('sandbox', sa.Boolean(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_connections_guest_id'), 'provider_connections', ['guest_id'], unique=False)
    op.create_index(op.f('ix_provider_connections_provider'), 'provider_connections', ['provider'], unique=False)
    op.add_column('stays', sa.Column('source', sa.String(length=32), server_default='manual', nullable=False))
    op.add_column('stays', sa.Column('provider_connection_id', sa.String(length=64), nullable=True))
    op.add_column('stays', sa.Column('external_ref', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_stays_provider_connection_id'), 'stays', ['provider_connection_id'], unique=False)
    op.create_unique_constraint('uq_stays_external_ref', 'stays', ['external_ref'])
    op.create_foreign_key(
        'fk_stays_provider_connection_id',
        'stays',
        'provider_connections',
        ['provider_connection_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_stays_provider_connection_id', 'stays', type_='foreignkey')
    op.drop_constraint('uq_stays_external_ref', 'stays', type_='unique')
    op.drop_index(op.f('ix_stays_provider_connection_id'), table_name='stays')
    op.drop_column('stays', 'external_ref')
    op.drop_column('stays', 'provider_connection_id')
    op.drop_column('stays', 'source')
    op.drop_index(op.f('ix_provider_connections_provider'), table_name='provider_connections')
    op.drop_index(op.f('ix_provider_connections_guest_id'), table_name='provider_connections')
    op.drop_table('provider_connections')
    # ### end Alembic commands ###
