"""initial schema

Revision ID: 897482151541
Revises: 
Create Date: 2026-06-04 11:28:56.444736

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897482151541'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featured_deals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('badge', sa.String(length=64), nullable=False),
    sa.Column('discount_label', sa.String(length=64), nullable=False),
    sa.Column('discount_note', sa.String(length=128), nullable=False),
    sa.Column('base_price_cents', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_category'), 'menu_items', ['category'], unique=False)
    op.create_table('stays',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=False),
    sa.Column('room_number', sa.String(length=32), nullable=False),
    sa.Column('check_in_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_categories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('accent', sa.String(length=16), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('base_price_cents', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('guest_id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('deal_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['travel_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['featured_deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_guest_id'), 'bookings', ['guest_id'], unique=False)
    op.create_table('check_ins',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('stay_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_stay_id'), 'check_ins', ['stay_id'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_transactions_created_at'), 'loyalty_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_guest_id'), 'loyalty_transactions', ['guest_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('stay_id', sa.String(length=64), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_placed_at'), 'orders', ['placed_at'], unique=False)
    op.create_index(op.f('ix_orders_stay_id'), 'orders', ['stay_id'], unique=False)
    op.create_table('digital_keys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('check_in_id', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_ins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_keys_check_in_id'), 'digital_keys', ['check_in_id'], unique=True)
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_digital_keys_check_in_id'), table_name='digital_keys')
    op.drop_table('digital_keys')
    op.drop_index(op.f('ix_orders_stay_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_placed_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_loyalty_transactions_guest_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_created_at'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index(op.f('ix_check_ins_stay_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_bookings_guest_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('travel_categories')
    op.drop_table('stays')
    op.drop_index(op.f('ix_menu_items_category'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_table('guests')
    op.drop_table('featured_deals')
    # ### end Alembic commands ###
