"""loyalty orchestrator providers and accounts

Revision ID: 974c6fed473d
Revises: 4dfd965adc45
Create Date: 2026-06-04 13:51:20.837586

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974c6fed473d'
down_revision: str | None = '4dfd965adc45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_color_hex', sa.String(length=7), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('linked', sa.Boolean(), nullable=False),
    sa.Column('discovered', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('detected_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id', 'provider_id', name='uq_loyalty_accounts_guest_provider')
    )
    op.create_index(op.f('ix_loyalty_accounts_guest_id'), 'loyalty_accounts', ['guest_id'], unique=False)
    op.create_index(op.f('ix_loyalty_accounts_provider_id'), 'loyalty_accounts', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loyalty_accounts_provider_id'), table_name='loyalty_accounts')
    op.drop_index(op.f('ix_loyalty_accounts_guest_id'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    op.drop_table('providers')
    # ### end Alembic commands ###
